import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import '@fontsource/silkscreen/700.css';
import { TypeAnimation } from 'react-type-animation';
export default function Profile() {
    return (_jsx(_Fragment, { children: _jsxs("div", { className: "h-screen px-5 pt-10 flex justify-center items-center gap-5 flex-col", style: {
                backgroundImage: 'linear-gradient(to right bottom, #000000, #17000a, #210017, #270023, #280034, #28003f, #26004b, #200158, #28015e, #2f0165, #37016b, #3f0071)',
            }, children: [_jsx("div", { className: "flex justify-center items-center h-1/3 max-w-[1024px]", children: _jsxs("div", { className: "flex flex-col gap-5 justify-center items-center text-white", children: [_jsx("h1", { className: "font-medium  text-2xl laptop:text-3xl text-center", children: "HELLO, I'M" }), _jsx("h1", { className: "font-bold text-3xl laptop:text-4xl text-center", children: "Alfian Vito Anggoro" }), _jsx("h1", { className: "font-normal text-xl laptop:text-2xl text-center", children: _jsx(TypeAnimation, { sequence: ['Web Developer', 1500, 'Fullstack Developer', 1500], speed: 50, style: { fontSize: '1em' }, repeat: Infinity }) })] }) }), _jsxs("div", { className: "flex justify-center items-center h-2/3 max-w-[1024px]", children: [_jsxs("div", { className: "hidden laptop:basis-1/3 h-full text-white laptop:flex flex-col justify-between items-start py-5", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-2xl font-bold", children: "Expertise" }), _jsx("p", { className: "text-xl font-normal", children: _jsx(TypeAnimation, { sequence: [
                                                    'Javascript',
                                                    1500,
                                                    'Typescript',
                                                    1500,
                                                    'PHP',
                                                    1500,
                                                ], speed: 50, style: { fontSize: '1em' }, repeat: Infinity }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-2xl font-bold", children: "Education" }), _jsx("p", { className: "text-xl font-normal", children: "Bachelor's Degree of Singaperbangsa Karawang University" })] })] }), _jsx("div", { className: "laptop:basis-1/3 w-full h-full ", children: _jsx("img", { src: "images/profiles/2.png", width: 100, height: 100, alt: "Alfian Vito Anggoro", className: "w-auto h-full" }) }), _jsxs("div", { className: "hidden laptop:basis-1/3 h-full text-white laptop:flex flex-col justify-between items-end text-end  py-5", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-2xl font-bold", children: "Interest" }), _jsx("p", { className: "text-xl font-normal", children: _jsx(TypeAnimation, { sequence: ['Flutter', 1500, 'Cloud', 1500, 'AI', 1500], speed: 50, style: { fontSize: '1em' }, repeat: Infinity }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-2xl font-bold", children: "Live in" }), _jsx("p", { className: "text-xl font-normal", children: "Bogor, Indonesia" })] })] })] })] }) }));
}
